### ISSUE TITLE
the question in the  elevationmapping.cpp file about Local mapping?

### ISSUE THREAD

**Issue by xiaowei520-lwl** [ZJU-Robotics-Lab/GEM#13]
1.how can we set the newKeyframeSignal ? the topic of new_keyframe  do not publish in the test.bag. do you have any idea about set the topic about it or any tips ?
2.in the function ElevationMapping::updateLocalMap(), the phase of // Local mapping//,it get the values of "elevation " and "traver",the it make judge so long  in the following and i do not understand it.can you help me?why make this if condition ?
if(((position.x() < (current_x - length_ * resolution_ / 2) || position.y() < (current_y - length_ * resolution_ / 2 )) && (delta_x > 0  && delta_y > 0))
           || ((position.x() > (current_x + length_ * resolution_ / 2 ) || position.y() > (current_y + length_ * resolution_ / 2 )) && (delta_x < 0 && delta_y < 0))
           || ((position.x() < (current_x - length_ * resolution_ / 2 ) || position.y() > (current_y + length_ * resolution_ / 2 )) && (delta_x > 0 && delta_y < 0))
           || ((position.x() > (current_x + length_ * resolution_ / 2 ) || position.y() < (current_y - length_ * resolution_ / 2 )) && (delta_x < 0 && delta_y > 0))
           || ((position.x() < (current_x - length_ * resolution_ / 2 )) && (delta_x > 0 && delta_y == 0))
           || ((position.x() > (current_x + length_ * resolution_ / 2 )) && (delta_x < 0 && delta_y == 0))
           || ((position.y() < (current_y - length_ * resolution_ / 2 )) && (delta_y > 0 && delta_x == 0))
           || ((position.y() > (current_y + length_ * resolution_ / 2 )) && (delta_y < 0 && delta_x == 0)))

**Comment by MaverickPeter** [comment]
@xiaowei520-lwl  The newKeyframeSignal is set by the SLAM system to generate submaps for further map optimization. You can advertise a newKeyframeSignal when the SLAM system generates a submap and optKeyframes when the SLAM system finish optimization If there is no need for map optimization, you can just ignore it. 
As for updateLocalMap, the judgment is to ensure the elevation is valid since -10 is an initial value. The condition "traver" is not necessary, we test it to filter out some obstacle points to make the map light, you can just delete it. The included if condition is about adding a "L" shape point to the submap for real time performance.

**Comment by xiaowei520-lwl** [comment]
thank you for your reply。do  you have any referral SLAM system ?   and what does the "L" shape means ? i donot have a clear understanding ,can you give me some advise ? Thank you very much ! because i am a green hand about the mapping system.

**Comment by MaverickPeter** [comment]
@xiaowei520-lwl  You can try to implement these to the Opensourced SLAM system by publishing a newKeyframeSignal and optKeyframes using our slam_msg package. About the "L" shape you can refer to our papers mentioned in README.

**Comment by xiaowei520-lwl** [comment]
ok，  i got it. thank you very much!
