### ISSUE TITLE
About Stereo-only version

### ISSUE THREAD

**Issue by RoboticsZhang** [ZJU-Robotics-Lab/GEM#6]
Thanks for your work! I'm wondering if you will release stereo-only version? It is supported in ETH package, where distance sensors(including stereo camera) and odometry are needed as the input.

**Comment by MaverickPeter** [comment]
@RoboticsZhang  Hi Zhang, we have a stereo-only version and will release it soon. 
The main reason for the procrastination is that we are trying to make the stereo-only version easier to use as an open-source project since the stereo-only version relies on an extra stereo matching library which requires a complex building and configuring process.

**Comment by RoboticsZhang** [comment]
Thanks a ton for your contribution! I'm looking forward to it! Can I see it in this month or next month?
By the way, I'm trying to implement elevation mapping on a micro platform where lidar is not suitable, so a stereo-only version will help me a lot. At present, I will try the ETH package but its real-time performance may not be satisfying.

**Comment by RoboticsZhang** [comment]
Thanks a ton for your contribution! I'm looking forward to it! Can I see it in this month or next month?
By the way, I'm trying to implement elevation mapping on a micro platform where lidar is not suitable, so a stereo-only version will help me a lot. At present, I will try the ETH package but its real-time performance may not be satisfying.

**Comment by MaverickPeter** [comment]
@RoboticsZhang If everything goes fine, you'll see it this month. As for the micro platforms, you mean what kind of platform, like nvidia tx2 or agx, notice that our GEM needs to have GPU supported.
