### ISSUE TITLE
About using KITTI data

### ISSUE THREAD

**Issue by TT22TY** [ZJU-Robotics-Lab/GEM#9]
Thank you for your sharing!

I try to use KITTI sequence 05 data for testing with lidar+camera version, however, the results is strange. 
I saw you said  the demo you provided was recorded with PandarQT with x axis point to left and y axis point to back. Does it need to change the axis of the data, or just modify somewhere in the code?
Thank you very much!

**Comment by TT22TY** [comment]
@MaverickPeter ,
 Hi, I was just wondering how will you use the  libelas, and when will you release stereo-only version, thank you ~

**Comment by MaverickPeter** [comment]
@TT22TY,
For the stereo-only version, first, you may refer to https://github.com/jeffdelmerico/cyphy-elas-ros and configure your stereo camera params and get a reconstructed point cloud, and then you can simply change the input point cloud topic to the reconstructed point cloud and enable GEM. We've already made some tests in simulation and everything goes fine. You can try this plan as a temporary solution. Since the code change is trivial to build a new branch and I'm in charge of other projects in recent days, there is no guarantee of releasing the stereo-only version, sorry about that.

**Comment by TT22TY** [comment]
@MaverickPeter ,
Thank you very much~
